name: angular_dart_demo
version: 0.0.1
dependencies:
  angular:
     git: /Users/naomib/github/angulardartdocs/angular.dart
  shadow_dom: any

dev_dependencies:
  unittest: any

transformers:
-  angular